### ISSUE TITLE
Deprecate unmix strategy and use a proxy by default

### ISSUE THREAD

**Issue by dazuma** [dazuma/blockenspiel#8]
Unmix is causing several major issues. Namely:

* MRI has deprecated the C interfaces that unmix was depending on, as of 1.9.3. I'm not certain whether MRI 2.0 has removed them altogether, but in any case, we can't depend on them existing in the future.
* The unmix semantics are that the change is dynamically rather than lexically scoped. This can cause confusion when you define blocks within the DSL because they lose their access to the DSL scope once the DSL terminates.

Because of this, I have decided to deprecate unmix, and make proxy the default implementation. Because this is a potentially breaking change, it will correspond to a major version update.

**Comment by dazuma** [comment]
Done in release 0.5.0

**Comment by ipmsteven** [comment]
> Because of this, I have decided to deprecate unmix, and make proxy the default implementation. Because this is a potentially breaking change, it will correspond to a major version update.

so a major version update would be 1.x.x?

**Comment by dazuma** [comment]
Because this is still 0.x, semver doesn't kick in yet, but I have defined "major" changes as 0.x -> 0.x+1.

**Comment by ipmsteven** [comment]
:+1:
