### ISSUE TITLE
 Failed to build gem native extension - jRuby 1.7.3

### ISSUE THREAD

**Issue by gsmedley** [dazuma/blockenspiel#9]
Was able to install with older versions of jRuby because it used to be possible to install Devkit. However, DevKit appears to have dropped support for more recent jRuby versions including 1.7.3

Seemed to have worked around this by adding an empty "make.bat" to my path.

<pre>
Building native extensions.  This could take a while...
ERROR:  Error installing blockenspiel:
ERROR: Failed to build gem native extension.
C:/jruby-1.7.3-build/bin/jruby.exe extconf.rb
make 'make' is not recognized as an internal or external command, 
operable program or batch file.
</pre>

Running under Windows

**Comment by dazuma** [comment]
Should no longer happen in 0.5.0 since the C extension has been removed.
